### ISSUE TITLE
The titles in the documentation are not align with the content

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#12]
**Describe the bug**
The titles in the documentation are not align with the content 

**To Reproduce**
1. Go to [the documentation page](https://design.payex.com/docs/getting-started/introduction)
2. Take a look "DesignGuide" and "Introduction"

**Possible fix**
Left align, use same horizontal padding as content.

**Screenshots**

![screen shot 2018-07-11 at 15 52 02](https://user-images.githubusercontent.com/16205454/42577183-344f1b32-8524-11e8-98b3-2bab5ed8d07b.png)

**Desktop:**
 - OS: MAC
 - Browser: Chrome 
 - Version 67 (Official Build) (64-bit)

**Comment by erikhallaraaker** [comment]
Yup, this should be aligned, atleast visually. Feel free to do a PR!
