### ISSUE TITLE
Inconsistent padding and alignment in topbar

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#13]
**Describe the bug**
1. The menu icon is not aligned with the text
2. The menu button and the Payex logo do not have the same margin to the vertical grey line
3. The PayEx logo does not look vertical aligned middle 

**To Reproduce**
1. Go to (developer.payex.com) 
2. Navigate to Documentation -> Topbar
3. Take a look at the top bar

**Possible fix**
1. Remove negative margin on the menu icon
2. Increase left side padding on logo
3. Reduce the logo size and use margin top to vertical align the menu text with the "P" in the logo.
 
**Screenshots**

![screen shot 2018-07-12 at 17 35 32](https://user-images.githubusercontent.com/16205454/42643775-4aa773da-85fa-11e8-83a3-c61a3a5273d4.png)

**Desktop:**
 - OS: MAC
 - Browser: Chrome 
 - Version 67 (Official Build) (64-bit)

**Comment by erikhallaraaker** [comment]
Agreed, this should be fixed
