### ISSUE TITLE
Weird border on .table.table-hover.table-striped

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#15]
**Describe the bug**
The table row border displays above the green hover indicator. 
The green hover indicator also overflows the table.

**To Reproduce**
1. Go to [developer.payex.com](https://design.payex.com/)
2. Navigate to Documentation -> Core -> Tables
3. Hover the first row of the "Hover striped table"

**Possible fix**
Put borders on cells and don't overflow the table to avoid weirdness?

**Screenshots**

Chrome
![screen shot 2018-07-13 at 13 32 48](https://user-images.githubusercontent.com/16205454/42691423-3de8b77c-86a8-11e8-9849-ddd1a987d411.png)

Firefox
![screen shot 2018-07-13 at 14 26 43](https://user-images.githubusercontent.com/16205454/42691639-2111d4ac-86a9-11e8-8e91-a44ce2502ba0.png)

**Desktop :**
 - OS: MAC
 - Browser: Chrome 
 - Version 67 (Official Build) (64-bit)

**Desktop :**
 - OS: MAC
 - Browser: Firefox 
 - Version 61.0.1 (64-bit)

**Comment by erikhallaraaker** [comment]
Yeah, I actullay noticed this a while back and was going to fix it, but some other stuff got in the way.. PR? :P

**Comment by erikhallaraaker** [comment]
Fixed with #21
