### ISSUE TITLE
Missing border on .table-striped in Firefox

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#19]
**Describe the bug**
The striped row loses it's right side border. 
It's seems this issue is caused by `border-collapse: collapse;` on `.table`.
This also seems to be the cause of #15.

**To Reproduce**
1. Go to (developer.payex.com) in Firefox
2. Navigate to Documentation -> Core -> Table
3. Take a look at the Striped table

**Possible fix**
Remove `border-collapse:collapse`. 
Add row border on table cells.
Update padding on first cell on hover table to prevent the text from moving.

**Screenshots**

![screen shot 2018-07-18 at 18 58 53](https://user-images.githubusercontent.com/16205454/42896348-eecf108c-8abc-11e8-9953-fb7697355ebc.png)

**Desktop:**
 - OS:  macOS High Sierra
 - Browser: Firefox
 - Version:  61

**Comment by erikhallaraaker** [comment]
Fixed with #21
