### ISSUE TITLE
Discussion: CSP: img-src

### ISSUE THREAD

**Issue by VikingTristan** [PayEx/design.payex.com#20]
**Checkbox and radio inputs use data schemas**

![schema](https://user-images.githubusercontent.com/26485094/42951364-4ff6de30-8b76-11e8-9170-49b7ce3967d2.JPG)

According to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src), using the `data:` schema is considered:

> Insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.

Although it isn't being used for scripts, it might be worth a discussion.

**To Reproduce**
1. Enable Content Security Policy

**Comment by erikhallaraaker** [comment]
I suggest you come up with a potential solution. We might be able to to recreate the images with pure css, using background-color, borders etc.

**Comment by hmosvoll** [comment]
@erikhallaraaker The selects also uses base64.

**Comment by Akswii** [comment]
Fixed by #112
