### ISSUE TITLE
Double auto-complete in documentation

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#213]
Double auto complete in documentation

**Possible fix**
Auto complete off? 
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Screenshots**
![screenshot 2019-02-08 at 10 35 30](https://user-images.githubusercontent.com/16205454/52470091-81d34300-2b8d-11e9-93d2-1c0d1108e31e.png)

**Dekstop:**
 - OS: macOS Mojave
 - Browser: Firefox Developer Editon 66

**Comment by erikhallaraaker** [comment]
Yeah, I thought this was already done.. Definately should be fixed.

@Akswii Maybe include this in the patch, if it hasn't been released yet?

**Comment by Akswii** [comment]
We fixed it for the other designguide. I'll add the fix to the next patch.
