### ISSUE TITLE
Vertical progress bar

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#22]
In setup we a _progress bar_ / _step bar_ with many steps, which is therefore better to display vertically. Maybe something we should support in the design guide?

**Context**

![screen shot 2018-07-23 at 16 54 35](https://user-images.githubusercontent.com/16205454/43084698-7b6a2560-8e99-11e8-9f1e-c804020af288.png)

Please note the wireframe is only added to show the use case, not as a detailed design proposal.

**Comment by erikhallaraaker** [comment]
Sounds like a good idea 👍

**Comment by hmosvoll** [comment]
Made a mvp vertical step bar for setup: http://setup.dev.bizi.no/CustomerSignatures.

**Comment by erikhallaraaker** [comment]
Implemented with #44
