### ISSUE TITLE
Panel footer without padding

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#223]
**Describe the bug**
I use web components and therefore wrap elements for conditionals which breaks the panel footer because it uses a [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator). 

```
<setup-display display-target="setup-file-upload" display-attribute="has-file">
 <footer>
  ...
 </footer>
</setup-display>
```

**To Reproduce**
- Create a panel with a footer 
- Wrap the footer with another element 

**Possible fix**
Add an optional class (`.panel-footer`).

We could just use a [descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator), but I prefer to find a general pattern for this scenario, even though multiple footers in the panel in quite unlikely.  

Maybe this applies to other components that use child combinator selectors ending with element such as `footer`?

**Desktop :**
 - OS: MAC
 - Browser: Firefox Developer Edition 
 - Version: 66

**Screenshots**
![screenshot 2019-02-15 at 14 24 59](https://user-images.githubusercontent.com/16205454/52859641-879ccb80-312d-11e9-957c-76894e8ac714.png)

**Comment by Akswii** [comment]
Agreed, will add.
