### ISSUE TITLE
px-script crashes in IE11

### ISSUE THREAD

**Issue by VikingTristan** [PayEx/design.payex.com#281]
## Px-script.js crashes on IE11 when used outside of the main documentation project.

**To Reproduce**
1. Open IE11
2. Load any px-script.js from 0.14.2 up to 2.0.2.
3. Open console

**Possible fix**

This seems to be a transpiling thing, make sure to support IE11 or ES5 basically.

**Screenshots**
From 2.0.2
![Capture](https://user-images.githubusercontent.com/26485094/54828613-dc93aa80-4cb4-11e9-958b-0f98e3256ab2.JPG)

From 0.14.2 (https://examples.design.payex.com/signup/)
![image](https://user-images.githubusercontent.com/26485094/54828926-9854da00-4cb5-11e9-9ad5-355603cadad5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Internet Explorer
 - Version 11

**Additional context**

Because it's crashing it renders a lot of components functionless. Try opening up a sheet component in the Design Guide example pages with IE11

**Comment by Akswii** [comment]
Fixed by release 2.0.3
