### ISSUE TITLE
Init only single instance of a component instead of all components of that type by providing the element id when calling init()

### ISSUE THREAD

**Issue by rudgutter** [PayEx/design.payex.com#291]
### Problem:
In a SPA we have a lot of problems initiating components like topbar, dialog, sheet, etc, and have to initiate them manually by calling for example `px.dialog.init()`. If several components have dialog, it is unnecessary for them all to call `px.dialog.init()`, but as we are not always using the same components together, each component has to make sure it is calling `init()`.

Each design guide component that requires that `init()` is run should accept an element id or a list of ids to prevent unnecessary inits of already initialized elements.

### Possible solution:
`px.dialog.init('delete-card-dialog')` or `px.dialog.init(['delete-card-dialog', ''delete-device-dialog])` to initialize only the wanted elements.

**Comment by Akswii** [comment]
Fix in progress.

**Comment by Akswii** [comment]
Fixed by #356
