### ISSUE TITLE
Remove margin bottom from all last-childs

### ISSUE THREAD

**Issue by stepandersen** [PayEx/design.payex.com#30]
It might be relevant for other than `<p>`, but consider adding this rule:
`p:last-child {
    margin-bottom: 0;
}`
It would turn
![image](https://user-images.githubusercontent.com/2443474/44794824-9a383e00-aba9-11e8-95d6-6d210a4054c7.png)
Into
![image](https://user-images.githubusercontent.com/2443474/44794894-be941a80-aba9-11e8-8732-ca70c133dbc9.png)

And fix both .panel-body and .panel footer. Worth considering. although it might be better to simply do
`.panel-body *:last-child {
    margin-bottom: 0;
}`

**Comment by erikhallaraaker** [comment]
This is related to #33 I think, which was fixed? @stepandersen @Akswii
