### ISSUE TITLE
Capitalised labels instead of uppercase labels

### ISSUE THREAD

**Issue by stepandersen** [PayEx/design.payex.com#309]
As many suggest, including the article https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/, users read lowercase words more easily than uppercase words.

I believe we should switch to capitalised labels. I think it looks better too.
![image](https://user-images.githubusercontent.com/2443474/55708188-94c78f80-59e5-11e9-9392-f01b01c749af.png)

**Comment by Akswii** [comment]
Agreed, will fix.
