### ISSUE TITLE
Modal-body padding

### ISSUE THREAD

**Issue by stepandersen** [PayEx/design.payex.com#31]
Modal-body rule `padding: 2rem 2rem 1rem;` is awkward. the docs looks okay since we use a `<p>` that has `p {
    margin-bottom: 1rem;
}` as the last child, but I suspect time will come when we won't have a `<p>` or `<table class="table">` at the end of that modal-body. `<img>`, `<div class="row">` or `<ul>` for instance.

`<ul>` has the margin-bottom rule `ol, ul {
    margin-top: 0;
    margin-bottom: 3px;
}` which is a bit awkward aswell.

**Comment by erikhallaraaker** [comment]
Modal is deprecated
