### ISSUE TITLE
Calling init() several times breaks if adding a listener to element that already has a listener

### ISSUE THREAD

**Issue by boye-s** [PayEx/design.payex.com#313]
It seems like calling `px.*.init()` breaks listeners if they already have been added.

After adding an element to the DOM and adding a listener by for example calling `px.expandable.init()` with Vue and then redrawing the DOM when the data in the component changes another call to `px.expandable.init()` does not work to re-initiate the listener.

Not sure about how to solve this, but maybe start by cleaning the list of registered listeners before registering new ones upon calling `px.*.init()`?

**Comment by Akswii** [comment]
We will soon release init by ID which will lessen this issue, but we will look into fixing this at a later time.
