### ISSUE TITLE
Page-title for h1-h6

### ISSUE THREAD

**Issue by stephanandersen** [PayEx/design.payex.com#324]
I would like a way to make headings of a page or section stand out.
A thin border-bottom is sufficient and a good solution as the border will also set the width of the content. (Is very relevant if the content is centered)
![image](https://user-images.githubusercontent.com/12971104/56126497-9e1fa180-5f7b-11e9-82f3-d7ed92f18e0a.png)

`<h3 class="page-title">MerchantName</h3>`
```
.page-title {
    border-bottom: 1px solid #e6e7e8;
}
```

I don't have a use case other than headings, might be correct to limit it to headings e.g. `.h3.page-title {`
I don't believe that `border-color` is from design guide though.

**Comment by Akswii** [comment]
Agreed, will add.
