### ISSUE TITLE
Breadcrumb inline-block media-query

### ISSUE THREAD

**Issue by stephanandersen** [PayEx/design.payex.com#325]
I believe this rule should have been removed when .breadcrumb was changed to use `flex`:
```
@media screen and (max-width: 767.98px)
ol.breadcrumb li, ul.breadcrumb li {
    display: inline-block;
}
```
It causes the breadcrumb `li`s to have different positions from 767px to 768px.
![image](https://user-images.githubusercontent.com/12971104/56144522-d38bb580-5fa2-11e9-9e80-3c8c1eecc55d.png)

**Comment by Akswii** [comment]
Will fix.
