### ISSUE TITLE
Select: Dropdown arrow covers text

### ISSUE THREAD

**Issue by stepandersen** [PayEx/design.payex.com#346]
![image](https://user-images.githubusercontent.com/2443474/57063883-02a16700-6cc5-11e9-933a-a1b570361125.png)

The problem becomes apparent when using `.col-auto`, `select.form-control` should have `padding-right: 1.75rem` (or so) to prevent the arrow from overlapping the text.

**Comment by Akswii** [comment]
Will fix.
