### ISSUE TITLE
Suggestion: Implement full-width container

### ISSUE THREAD

**Issue by stepandersen** [PayEx/design.payex.com#37]
There is a need to be able to let (typically) a table take the full width of a section. Håkon has an example of this usage in the srm setup tool.

A suggestion is to add a full-width container element that has no padding and that adds a padding to the leftest and rightest columns of the table.

Håkon: Please help me describe this issue properly :)

**Comment by hmosvoll** [comment]
Tables in panels looks better if the table ignore the panel padding and start/ends at the edge of the panel, but the text content inside the table stil needs to align horizontally with other text in the panel.

![screen shot 2018-09-06 at 17 26 29](https://user-images.githubusercontent.com/16205454/45167847-502f0800-b1fa-11e8-89f8-312a5bd24acc.png)

http://setup.dev.bizi.no/1/control-registration

**Comment by erikhallaraaker** [comment]
Fixed in #65
