### ISSUE TITLE
Fix: Dropdowns with border radius on mac

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#38]
**Describe the bug**
Dropdowns on mac gets border radius. 

**Screenshots**

![screen shot 2018-09-06 at 17 19 44](https://user-images.githubusercontent.com/16205454/45167517-95066f00-b1f9-11e8-8541-56c141e120c0.png)

**Desktop (please complete the following information):**
- OS: MAC
- Browser Chrome
- Version 68

**Comment by Akswii** [comment]
Fixed by @erikhallaraaker https://github.com/PayEx/design.payex.com/commit/5bf0bbeafafe2425d69fb8b800f04e5393bc78d2

**Comment by asbjornu** [comment]
@erikhallaraaker, @Akswii: Protip: Write `fixes #38` in pull requests and/or commit messages so GitHub can close issues and link them to their resolving commit automatically.

**Comment by erikhallaraaker** [comment]
Uhm, I don't think this is fixed...
