### ISSUE TITLE
[EXPERIMENTAL] Text in select input hidden due to excessive padding

### ISSUE THREAD

**Issue by erikhallaraaker** [PayEx/design.payex.com#390]
**Describe the bug**

You can not see the options in a `<select>`, this is due to padding and height restriction on `.form-control`.

**To Reproduce**
1. Go to https://design.payex.com/experimental/docs/components/input-group/#with-select
2. ???
3. See error

**Expected behavior**

I expected to see the options within the `<select>`

**Actual behavior**

I do not see the options within the `select`

**Possible fix**
Remove `height` and update padding.

```css
.form-control {
    padding: 0.4rem 0.75rem;
   ...
}
```

**Screenshots**
![image](https://i.gyazo.com/5d164c9242595827b6066a567e3468a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by Akswii** [comment]
Fixed by https://github.com/PayEx/design.payex.com/commit/63ad874963daeaae9f53e671810cb531252643dc
