### ISSUE TITLE
Menu slider does not close when link clicked if click does not trigger page load

### ISSUE THREAD

**Issue by rudgutter** [PayEx/design.payex.com#42]
Menu slider does not close when clicked if click does not trigger page load aka uses a SPA router.

1. Implement Topbar
2. Make link in menu slider to SPA route.
3. Click link.
4. Slider does not close on link click. Will close if click is registered outside of slider or page load is triggered.

**Expected behavior**

Expected menu slider to close with animation similar to when clicking outside of menu slider.
NB! A fix for this should maybe come with different modes, as an animation trigger at the same time as a page load might look weird if animation is not completed before page loads.

**Actual behavior**

Route is navigated to, but menu slider does not close.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 69

**Comment by stepandersen** [comment]
Make this as an option, either a class or attribute that enables the behavior or class or attribute that prevents the behavior

**Comment by stepandersen** [comment]
In angular I think you might do
`<a href="/#/awesome-section">Awesome Section</a>`

**Comment by erikhallaraaker** [comment]
Actually it wont be a problem, as "links" to navigate to the next page of the menu is `<span>` elements, so we can add a rule that makes all `<a>` tags close the menu regardless of href.

**Comment by erikhallaraaker** [comment]
Fixed with 767cc2aa918daeda8fc07ccba268738f743c76af.
