### ISSUE TITLE
I need a way to close a dialog and a sheet programmatically.

### ISSUE THREAD

**Issue by boye-s** [PayEx/design.payex.com#45]
I am not able to close a dialog or sheet programmatically. Let's say a button click triggers an ajax call and we're waiting for a response. We need to be able to wait for the response before closing the dialog or sheet.

`px.closeDialog('dialog-id')` and `px.closeSheet('sheet-id')` would be perfect.

The alternative is a hidden button that is clicked programmatically when the operation we are waiting for is completed.

**Comment by erikhallaraaker** [comment]
Yeah, this is a probably a good idea to include. It should probably be `px.dialog.close("id")` and `px.sheet.close("id")` though, so it is under the correct component
