### ISSUE TITLE
Margin and padding spacing utilities no longer work.

### ISSUE THREAD

**Issue by rudgutter** [PayEx/design.payex.com#46]
**Describe the bug**
Spacing utilities like the class `mb-1` no longer adds 1rem of margin to bottom of element.

**Expected behavior**
Spacing utilities like the class `mb-1` adds 1rem of margin to bottom of element.

***What I want***
![What I want](https://imgur.com/lVwQKsd.png)

***What I got***
![What I got](https://imgur.com/foySel5.png)

**Comment by erikhallaraaker** [comment]
This was previously implemented like they do in [bootstrap v4](https://getbootstrap.com/docs/4.0/utilities/spacing/).

It was removed in 932705dc0478a514459e9906f46172c7d7ee0c45 on request by @stepandersen as it gave too many options on the layout.
This might be a good usecase for it though.

**Comment by erikhallaraaker** [comment]
Resolved with 4a0e59aad18b231cc22e10ded46a1f74ddc89abe, released with [0.12.1](https://github.com/PayEx/design.payex.com/releases/tag/0.12.1).
