### ISSUE TITLE
Dialog box adds right padding

### ISSUE THREAD

**Issue by NullableInt** [PayEx/design.payex.com#47]
When dialogbox is opened it adds 17px right padding with the class .dialog-open

Provide a more detailed introduction to the issue itself, and why you consider it to be a bug.

**To Reproduce**
1. Go to https://design.payex.com/docs/components/dialog
2. Click on Open dialog
3. See error

**Expected behavior**

Not having padding on body.

**Actual behavior**

Padding on body when there is no scroll-bar

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Chrome]
 - Version [69]

**Comment by rudgutter** [comment]
This is also true for the Sheet component.

**Comment by erikhallaraaker** [comment]
Resolved in #54, will be included in 0.13.0
