### ISSUE TITLE
Weird break in doc sidebar

### ISSUE THREAD

**Issue by hmosvoll** [PayEx/design.payex.com#50]
The sidebar items line breaks in a way that don't follow the over all spacing.

**To Reproduce**
1. Go to [design.payex.com](https://design.payex.com) (_Edited_)
2. Navigate to Documentation 
3. Resize window to produce line breaks in doc sidebar

**Possible fix**
Padding on `<ul>`, not `<a>`

**Screenshots**

![screen shot 2018-10-09 at 14 24 44](https://user-images.githubusercontent.com/16205454/46669341-6bad7a00-cbcf-11e8-9193-62cdc81374fb.png)

**Desktop**
 - OS: MAC
 - Browser Chrome
 - Version 69

**Comment by erikhallaraaker** [comment]
I assume you meant <design.payex.com> and not <developer.payex.com> :P
But yeah, it should be fixed!

**Comment by hmosvoll** [comment]
@erikhallaraaker Yes! Fixed :)

**Comment by erikhallaraaker** [comment]
Fixed by df29e40094b50799990ce637ee923d953b7ce464
