### ISSUE TITLE
Suggestion: Show current date in date picker

### ISSUE THREAD

**Issue by steff-o** [PayEx/design.payex.com#55]
When selecting a date it would be nice if today is somehow marked in the calendar. When opening a date picker it often has today selected as default, but if one selects another date it helps if today is marked somehow to quickly be able to estimate how the selected date relates to today. It also helps if one wants to quickly select today again after fiddling around in the date picker.

My suggestion would be to mark today in the calendar with a dimmed down color background or border.

**Comment by Akswii** [comment]
We replaced rome with https://flatpickr.js.org/. Fixed by #138
