### ISSUE TITLE
Grid system: Alignment.

### ISSUE THREAD

**Issue by VikingTristan** [PayEx/design.payex.com#9]
Design Guide already uses the grid system from Bootstrap v4, but not all classes are implemented. It would be huge, quite possibly the greatest implementation, if the [alignment section](http://getbootstrap.com/docs/4.1/layout/grid/#alignment) could also be a part of this amazing project.

**Comment by erikhallaraaker** [comment]
Will be implemented

**Comment by erikhallaraaker** [comment]
Implemented with 12eaa8289e7ad4a64dd0c81e7f9858f7ef95ee59, will be included in next release.
